Command: /home/ngochoan/.espressif/python_env/idf5.5_py3.10_env/bin/python /home/ngochoan/esp/esp-idf/tools/idf_monitor.py -p /dev/ttyUSB0 -b 115200 --toolchain-prefix riscv32-esp-elf- --target esp32c3 --revision 3 --decode-panic backtrace /home/ngochoan/esp/rtos/control_motor/build/control_motor.elf /home/ngochoan/esp/rtos/control_motor/build/bootloader/bootloader.elf -m '/home/ngochoan/.espressif/python_env/idf5.5_py3.10_env/bin/python' '/home/ngochoan/esp/esp-idf/tools/idf.py'
[0;33m--- esp-idf-monitor 1.7.0 on /dev/ttyUSB0 115200[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H[0m
[0m--- 0x403cbf10: [0;33mesp_bootloader_get_description[0m[0m at [0;32m/home/ngochoan/esp/esp-idf/components/esp_bootloader_format/esp_bootloader_desc.c[0m[0m:[1;31m38[0m
[0m--- 0x403ce710: [0;33mesp_flash_encryption_enabled[0m[0m at [0;32m/home/ngochoan/esp/esp-idf/components/bootloader_support/src/flash_encrypt.c[0m[0m:[1;31m87[0m
[0m--- 0x403cbf28: [0;33mcall_start_cpu0[0m[0m at [0;32m/home/ngochoan/esp/esp-idf/components/bootloader/subproject/main/bootloader_start.c[0m[0m:[1;31m25[0m
[1;31m--- Error: device reports readiness to read but returned no data (device disconnected or multiple access on port?)[0m
[0;33m--- Waiting for the device to reconnect[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m[0m
[0m
